### ISSUE TITLE
Installation help

### ISSUE THREAD

**Issue by SunnyPage** [lifeisbeautifu1/social-media-app#1]
Please help me which steps need to be completed to install locally. I started the client and server. But I get errors. "Cannot read properties of undefined (reading 'username')"
Perhaps my .env is not complete. I'm using node-v18.17.0. Is there any video or instruction?

**Comment by lifeisbeautifu1** [comment]
Hi! Im sorry, this repo is a little bit confusing because it contains the production build. If you want to run it locally you need to change a couple things. In the `backend/src/index.ts` change cors to localhost. Do the same in the frontend folder for axios and sockets. It should look like the following. Also make sure to fill the env file with your mongodb uri, cloudinary credentials for photo uploads and mailgun credentials for email confirmation. It will work without them too, but mongodb uri is required. It should look like mine.
<img width="1440" alt="Screenshot 2023-10-27 at 8 57 48 AM" src="https://github.com/lifeisbeautifu1/Social/assets/75017126/7239d499-7f4b-485d-8216-1ff90c9aa577">
<img width="1440" alt="Screenshot 2023-10-27 at 8 59 02 AM" src="https://github.com/lifeisbeautifu1/Social/assets/75017126/41fdcaf5-59b8-48ea-b1ee-2598642f5a25">
<img width="1440" alt="Screenshot 2023-10-27 at 8 59 08 AM" src="https://github.com/lifeisbeautifu1/Social/assets/75017126/ca673cb0-830d-48fc-9910-e7d2fdb19d18">
<img width="1440" alt="Screenshot 2023-10-27 at 9 01 03 AM" src="https://github.com/lifeisbeautifu1/Social/assets/75017126/4234e18b-5a98-442f-900b-4434b8888579">
<img width="1440" alt="Screenshot 2023-10-27 at 8 56 40 AM" src="https://github.com/lifeisbeautifu1/Social/assets/75017126/7559a00c-e8a5-4068-bece-c073935a3e40">

**Comment by SunnyPage** [comment]
Thank you very much, this works. I want to try to develop the project, for example, add an admin panel and other functionality.
